// Date format is YYYY-MM-DD

// const staticAllergens: Allergen[] = [
//   { allergen_id: 226, description: "Eggs" },
//   { allergen_id: 227, description: "Milk" },
//   { allergen_id: 228, description: "Wheat" },
//   { allergen_id: 229, description: "Soy" },
//   { allergen_id: 230, description: "Peanuts" },
//   { allergen_id: 231, description: "Tree Nuts" },
//   { allergen_id: 232, description: "Fish" },
//   { allergen_id: 233, description: "Crustacean" },
//   { allergen_id: 234, description: "Sesame Seeds" },
// ];
// const staticLocations: Location[] = [
//   { location_id: 87, location_name: "Parkside" },
//   { location_id: 86, location_name: "Hillside" },
//   { location_id: 85, location_name: "Beachside" },
// ];

// // Static meal types data
// const staticMealTypes: MealType[] = [
//   { meal_type_id: 113, meal_type_name: "Breakfast" },
//   { meal_type_id: 114, meal_type_name: "Brunch" },
//   { meal_type_id: 115, meal_type_name: "Lunch" },
//   { meal_type_id: 116, meal_type_name: "Dinner" },
// ];

export const CUT_OFF_DATE = "2024-12-18";

export const temporaryMenus: {
  [date: string]: { menuName: string; menuItems: any[] };
} = {
  "2024-12-09": {
    menuName: "Finals Week Menu: 12/9",
    menuItems: [
      {
        item_name: "Chocolate Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Cajun Potatoes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Kale and Sweet Potato Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Greek Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Shrimp Tempura Udon",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Harissa Chicken",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Cauliflower and Quinoa Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Kale and Sweet Potato Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Greek Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Tenders",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Texas Style Pork Ribs",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Spicy Gardein Chicken Stir-Fry",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-10": {
    menuName: "Finals Week Menu: 12/10",
    menuItems: [
      {
        item_name: "Biscuit and Country Gravy",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Kielbasa",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hashbrown",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Corn Chowder",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Turkey Club Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Filipino Pork",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Steak Quesadilla",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Pasta w/ Gardein Meat Sauce",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Corn Chowder",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Turkey Club Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Meat Lasagna",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Barbacoa Chicken Mulita",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Korean Gardein Beef Bowl",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-11": {
    menuName: "Finals Week Menu: 12/11",
    menuItems: [
      {
        item_name: "Soyrizo, Egg, Potato and Cheese Burrito",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Turkey Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tater Tots",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Pork Posole",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Caesar Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Shrimp Tacos",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "BBQ Chicken Sandwich",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name:
          "Vegan/Vegetarian: Gardein Chicken Alfredo Pasta w/ Broccoli",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Pork Posole",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Caesar Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grilled Beef Flank Steak w/ Chimichurri Sauce",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Loaded Mashed Potato Bar",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Plant-Based Chicken Tenders",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-12": {
    menuName: "Finals Week Menu: 12/12",
    menuItems: [
      {
        item_name: "Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Rice Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Caprese Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Orange Chicken Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Pasta Marinara",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef w/ Black Pepper Sauce",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Rice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Caprese Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Hamburger Bar",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Mac and Cheese",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Stuffed Zucchini Boat",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-13": {
    menuName: "Finals Week Menu: 12/13",
    menuItems: [
      {
        item_name: "French Toast",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potatoes O’Brien",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Clam Chowder",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Apple Walnut Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Lemon Pepper Salmon",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Plum Sauce Meatballs",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Edamame Fried Rice w/ Tofu",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Clam Chowder",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Apple Walnut Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Red Chile Colorado",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Fish Tacos",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Chicken and Broccoli Stir-Fry",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-14": {
    menuName: "Finals Week Menu: 12/14",
    menuItems: [
      // Brunch
      {
        item_name: "Not available",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Not available",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Not available",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      // Dinner
      {
        item_name: "Not available",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Not available",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Not available",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-15": {
    menuName: "Finals Week Menu: 12/15",
    menuItems: [
      {
        item_name: "Waffle Sticks",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Smoothie of the Day",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Parmesan",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Baked Tortellini w/ Spinach",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Spicy Tofu and Eggplant",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-16": {
    menuName: "Finals Week Menu: 12/16",
    menuItems: [
      {
        item_name: "French Toast",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tator Tots",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Chicken Gumbo Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tuna Rotini Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Hot Chicken Sandwich",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Beef Tri-Tip with Mustard Sauce",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Buddha Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Gumbo Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Tuna Rotini Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Teriyaki Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Taquitos",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Vegan Creamy Mac and Cheese",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-17": {
    menuName: "Finals Week Menu: 12/17",
    menuItems: [
      {
        item_name: "Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Nacho Salsa Bar",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Taco Bar",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Tofu Fajitas",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Italian Herb Pasta Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Curry Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Loaded Grilled Cheese Sandwich",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Teriyaki Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-18": {
    menuName: "Finals Week Menu: 12/18",
    menuItems: [
      {
        item_name: "Waffle Sticks",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Breakfast Sausage",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Quesadilla",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Sweet and Sour Pork",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Kung Pao Gardein Chicken",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Coming Soon!",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coming Soon!",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
};
