// Date format is YYYY-MM-DD

// const staticAllergens: Allergen[] = [
//   { allergen_id: 226, description: "Eggs" },
//   { allergen_id: 227, description: "Milk" },
//   { allergen_id: 228, description: "Wheat" },
//   { allergen_id: 229, description: "Soy" },
//   { allergen_id: 230, description: "Peanuts" },
//   { allergen_id: 231, description: "Tree Nuts" },
//   { allergen_id: 232, description: "Fish" },
//   { allergen_id: 233, description: "Crustacean" },
//   { allergen_id: 234, description: "Sesame Seeds" },
// ];
// const staticLocations: Location[] = [
//   { location_id: 87, location_name: "Parkside" },
//   { location_id: 86, location_name: "Hillside" },
//   { location_id: 85, location_name: "Beachside" },
// ];

// // Static meal types data
// const staticMealTypes: MealType[] = [
//   { meal_type_id: 113, meal_type_name: "Breakfast" },
//   { meal_type_id: 114, meal_type_name: "Brunch" },
//   { meal_type_id: 115, meal_type_name: "Lunch" },
//   { meal_type_id: 116, meal_type_name: "Dinner" },
// ];

// CUT OFF DATE: EDIT THIS
// YYYY - MM - DD
export const CUT_OFF_DATE = "2025-05-12";

export const temporaryMenus: {
  [date: string]: { menuName: string; menuItems: any[] };
} = {
  "2024-12-09": {
    menuName: "Finals Week Menu: 12/9",
    menuItems: [
      {
        item_name: "Frech Toast",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Turkey Sausage Patties",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Homestyle Potatoes",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Italian Wedding Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Grilled Italian Sausage Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Chicken Karaage Bowl",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Pork Tacos",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Italian Wedding Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Buffalo Chicken Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Flank Steak w/ Chimichurri",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Creamy Tomato Tortellini",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chocolate Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Cajun Potatoes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Kale and Sweet Potato Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Greek Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Shrimp Tempura Udon",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Harissa Chicken",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Cauliflower and Quinoa Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Kale and Sweet Potato Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Greek Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Tenders",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Texas Style Pork Ribs",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name:
          "Vegan/Vegetarian: Spicy Vegan/Vegetarian: Gardein Chicken Stir-Fry",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chilaquiles Rojos",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Turkey Sausage Patties",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Southwestern Potatoes",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Butternut Squash Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken and Dumpling Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "BBQ Pulled Pork Sandwich",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Breaded Chicken Creamy Chipotle Pasta",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Buddha Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Butternut Squash Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken and Dumpling Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Taquitos",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Butter Chicken",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Creamy Vegan Cauliflower Mac and Cheese",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-10": {
    menuName: "Finals Week Menu: 12/10",
    menuItems: [
      {
        item_name: "Breakfast Burrito",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Kielbasa",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Pork Pozole",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Banh Mi Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Teriyaki Chicken",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Teriyaki Beef",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Pork Pozole",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Shrimp Basket",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Pork w/ Chile Rojo",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Crispy Tofu w/ Eggplant",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Biscuit and Country Gravy",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Kielbasa",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hashbrown",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Corn Chowder",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Turkey Club Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Filipino Pork",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Steak Quesadilla",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Pasta w/ Gardein Meat Sauce",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Corn Chowder",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Turkey Club Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Meat Lasagna",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Barbacoa Chicken Mulita",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Korean Gardein Beef Bowl",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Banana Pancakes",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Browns",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potato Leek Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Tortilla Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Filipino Pork",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Beef Hot Dog Bar",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Fried Mushroom Tacos",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Potato Leek Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Tortilla Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken and Black Pepper Sauce",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Nacho Bar",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Black Bean Tostones",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-11": {
    menuName: "Finals Week Menu: 12/11",
    menuItems: [
      {
        item_name: "Pineapple Fried Rice",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Pork Sausage Links",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Country Potatoes",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Chicken Noodle Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Chicken Pesto Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Beef Pot Roast",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Fajitas",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Chicken Noodle Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Gyro Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Taco Bar",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Chile Relleno",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Soyrizo, Egg, Potato and Cheese Burrito",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Turkey Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tater Tots",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Pork Posole",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Caesar Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Shrimp Tacos",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "BBQ Chicken Sandwich",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name:
          "Vegan/Vegetarian: Gardein Chicken Alfredo Pasta w/ Broccoli",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Pork Posole",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Caesar Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grilled Beef Flank Steak w/ Chimichurri Sauce",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Loaded Mashed Potato Bar",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Plant-Based Chicken Tenders",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Breakfast Burrito",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Pork Links",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Country Potatoes",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Orange Chicken",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Pasta Beef Bolognese",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Vegan Irish Stew",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Noodle Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Cajun Fish",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Bulgogi Fries",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Fajitas",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-12": {
    menuName: "Finals Week Menu: 12/12",
    menuItems: [
      {
        item_name: "Egg and Sausage English Muffin Sandwich",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Chorizo Patties",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potato Hash",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Potato Bacon Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Breakfast Burger",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Tandoori Chicken",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Kung Pao Gardein Beef",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Potato Bacon Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Turkey Club Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Orange Chicken",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Thai Chickpea Curry",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },

      {
        item_name: "Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Rice Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Caprese Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Orange Chicken Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Pasta Marinara",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef w/ Black Pepper Sauce",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Rice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Caprese Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Hamburger Bar",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Mac and Cheese",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Stuffed Zucchini Boat",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Biscuits and Country Gravy",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Turkey Bacon",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Broccoli Cheddar Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Caldo de Res",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Tenders",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Beef Tri-Tip w/ Caramelized Onions",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Chicken Stir-Fry",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Broccoli Cheddar Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Caldo de Res",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chipotle Chicken Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Mac and Cheese",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Vegetable Barley Stew",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-13": {
    menuName: "Finals Week Menu: 12/13",
    menuItems: [
      {
        item_name: "Chilaquiles",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Grilled Flank Steak",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Papas a la Mexicana",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Clam Chowder",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Fish and Chips",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Spicy Crusted Salmon w/ Coconut Sauce",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Cheese Ravioli",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Clam Chowder",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Chicken Tenders and Fries",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Herb Roasted Chicken",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Spicy Harissa Tofu",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },

      {
        item_name: "French Toast",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potatoes O’Brien",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Clam Chowder",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Apple Walnut Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Lemon Pepper Salmon",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Plum Sauce Meatballs",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Edamame Fried Rice w/ Tofu",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Clam Chowder",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Apple Walnut Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Red Chile Colorado",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Fish Tacos",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Chicken and Broccoli Stir-Fry",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Ham, Egg and Cheese Croissant Sandwich",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Chicken and Apple Sausage",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potatoes O’Brien",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Clam Chowder",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Fish Tacos",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Shawarma Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Thai Curry Tofu",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Minestrone Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Clam Chowder",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Lemon Herb Chicken",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Coconut Shrimp",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Tofu Fried Rice",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-14": {
    menuName: "Finals Week Menu: 12/14",
    menuItems: [
      {
        item_name: "Waffle Sticks",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Grilled Ham",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },

      {
        item_name: "Soup: Broccoli Cheddar Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Burrito Bowl",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Stir-Fry Gardein Chicken",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Broccoli Cheddar Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Teriyaki Burger",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Pasta Bar",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Tofu Fried Rice",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Pancakes",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Kielbasa",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Tater Tots",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Vegetarian Chili",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Miso Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef's Choice",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Vegetarian Chili",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Miso Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Tikka Masala",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Shrimp Pesto Pasta",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Enchilada Scaloppine",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-15": {
    menuName: "Finals Week Menu: 12/15",
    menuItems: [
      {
        item_name: "French Toast Sticks",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Sausage Patties",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Home Potatoes",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },

      {
        item_name: "Soup: Chicken Noodle Soup",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Chicken BBQ",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Saltado",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Chicken Noodle Soup",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Grilled Cheese Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Chicken Fried Steak",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Vegetable Lasagna",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Waffle Sticks",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Smoothie of the Day",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Parmesan",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Baked Tortellini w/ Spinach",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Spicy Tofu and Eggplant",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-16": {
    menuName: "Finals Week Menu: 12/16",
    menuItems: [
      {
        item_name: "Ham and Cheese Croissant Sandwich",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Chorizo Patties",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potato Hash",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Lobster Bisque",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Chicken Quesadilla",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Asada Fries",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Creamy Cheese Ravioli w/ Spinach",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Lobster Bisque",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Fish and Chips",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Chicken Piccata",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Spicy Harissa Tofu",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "French Toast",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tator Tots",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Chicken Gumbo Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tuna Rotini Salad",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Hot Chicken Sandwich",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Beef Tri-Tip with Mustard Sauce",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Vegan/Vegetarian: Buddha Bowl",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Gumbo Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Miso Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Tuna Rotini Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Teriyaki Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef Taquitos",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Vegan Creamy Mac and Cheese",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "French Toast",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Canadian Bacon",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Browns",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Broccoli Cheddar Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken and Rice Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Yucatan Chicken Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Baked Ziti",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Potato and Cauliflower Curry",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Broccoli Cheddar Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken and Rice Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "BBQ Chicken Flatbread",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Kalbi Beef Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Kung Pao Tofu",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-17": {
    menuName: "Finals Week Menu: 12/17",
    menuItems: [
      {
        item_name: "Ham, Egg, and Cheese English Muffin Sandwich",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Pork Links",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Potatoes O'Brien",
        location_id: 85,
        meal_type_id: 113,
        allergens: [],
        location: "Beachside",
        meal_type: "Breakfast",
      },

      {
        item_name: "Soup: Corn Chowder",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Grill Station: Philly Steak Sandwich",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Entrée: Chicken Marsala",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Pasta alla Norma",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Soup: Corn Chowder",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Grill Station: Spicy Chicken Sandwich",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Entrée: Popcorn Chicken",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Thai Chickpea Curry",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Pancakes",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Sausage Links",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Hash Brown",
        location_id: 87,
        meal_type_id: 113,
        allergens: [],
        location: "Parkside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Nacho Salsa Bar",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Taco Bar",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Tofu Fajitas",
        location_id: 87,
        meal_type_id: 115,
        allergens: [],
        location: "Parkside",
        meal_type: "Lunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Italian Herb Pasta Salad",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Curry Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Loaded Grilled Cheese Sandwich",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Teriyaki Bowl",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Sausage, Egg, and Cheese English Muffin Sandwich",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Bacon",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Southwestern Potatoes",
        location_id: 86,
        meal_type_id: 113,
        allergens: [],
        location: "Hillside",
        meal_type: "Breakfast",
      },
      {
        item_name: "Vegetable Noodle Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Chicken Dumpling Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Beef Fajitas",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Mongolian Chicken",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Meatball Pasta",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegetable Noodle Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Dumpling Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Build Your Own Grain Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Steak Quesadilla",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Popcorn Chicken Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Beef Teriyaki Bowl",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
  "2024-12-18": {
    menuName: "Finals Week Menu: 12/18",
    menuItems: [
      {
        item_name: "Pancakes",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Kielbasa",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },
      {
        item_name: "Tater Tots",
        location_id: 85,
        meal_type_id: 114,
        allergens: [],
        location: "Beachside",
        meal_type: "Brunch",
      },

      {
        item_name: "Entrée: Taquito Bar",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },
      {
        item_name: "Vegan/Vegetarian: Edamame and Tofu Fried Rice",
        location_id: 85,
        meal_type_id: 115,
        allergens: [],
        location: "Beachside",
        meal_type: "Lunch",
      },

      {
        item_name: "Entrée: Hamburger Bar",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Pasta and Gardein Meat Sauce",
        location_id: 85,
        meal_type_id: 116,
        allergens: [],
        location: "Beachside",
        meal_type: "Dinner",
      },
      {
        item_name: "Waffle Sticks",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Breakfast Sausage",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Hash Brown Patties",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice",
        location_id: 87,
        meal_type_id: 114,
        allergens: [],
        location: "Parkside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef’s Choice Soup",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Quesadilla",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Sweet and Sour Pork",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Kung Pao Gardein Chicken",
        location_id: 87,
        meal_type_id: 116,
        allergens: [],
        location: "Parkside",
        meal_type: "Dinner",
      },
      {
        item_name: "Hawaiian Breakfast",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Scrambled Eggs",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Ham/Spam",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Country Potatoes/Rice",
        location_id: 86,
        meal_type_id: 114,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Beef and Barley Soup",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Chef's Choice",
        location_id: 86,
        meal_type_id: 115,
        allergens: [],
        location: "Hillside",
        meal_type: "Brunch",
      },
      {
        item_name: "Tomato Basil Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef and Barley Soup",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Chicken Alfredo Pasta",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Beef and Vegetable Stir-Fry",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
      {
        item_name: "Vegan/Vegetarian: Gardein Chicken Barbacoa Tacos",
        location_id: 86,
        meal_type_id: 116,
        allergens: [],
        location: "Hillside",
        meal_type: "Dinner",
      },
    ],
  },
};
